# Generated by Django 2.2 on 2019-04-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='education',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='languages',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
