# Generated by Django 2.2 on 2019-04-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chat_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='category',
            new_name='categories',
        ),
    ]
