# Generated by Django 2.2 on 2019-05-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlog',
            name='patient_notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionlog',
            name='therapist_notes',
            field=models.TextField(null=True),
        ),
    ]
