# Generated by Django 2.2 on 2019-05-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190502_1614'),
        ('main', '0006_auto_20190502_1024'),
    ]

    operations = [
    ]
