# Generated by Django 2.2 on 2019-05-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20190502_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='occured',
            field=models.BooleanField(null=True),
        ),
    ]
