# Generated by Django 2.2 on 2019-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190502_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
