# Generated by Django 2.2 on 2019-05-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190505_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='working_day',
            field=models.CharField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thrusday'), (5, 'Friday'), (6, 'Saturday')], max_length=30, null=True),
        ),
    ]
