# Generated by Django 2.2 on 2019-05-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_therapist_working_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='working_day',
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Match'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='working_days',
            field=models.ManyToManyField(to='main.Day'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='working_hours',
            field=models.ManyToManyField(to='main.Hour'),
        ),
    ]
