# Generated by Django 2.2 on 2019-05-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190507_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='name',
            field=models.IntegerField(),
        ),
    ]
