# Generated by Django 2.2 on 2019-05-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190507_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapysession',
            name='match',
        ),
        migrations.AddField(
            model_name='therapysession',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Patient'),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Therapist'),
        ),
    ]
