# Generated by Django 2.2 on 2019-05-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190507_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='daycode',
            field=models.IntegerField(null=True),
        ),
    ]
