# Generated by Django 2.2 on 2019-05-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='match',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='match',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
