# Generated by Django 2.2 on 2019-05-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190508_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapysession',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
