# Generated by Django 2.2 on 2019-05-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_therapist_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images/'),
        ),
    ]
