# Generated by Django 2.2 on 2019-05-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190512_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images/'),
        ),
    ]
